### ISSUE TITLE
App crashing

### ISSUE THREAD

**Issue by Jacksonhayes** [jahirfiquitiva/Kuper#81] opened 2023-07-05 15:08 UTC
### Requirements

- [X] I have verified there are no duplicate active or recent bugs, questions, or requests

### Kuper Version

2.4.5

### Android Version

13.0

### Device Manufacturer

Xiaomi

### Device Name

Redmi K20 Pro

### What happened?

app is crashing .
i,ve tried few steps.
1. app is crashing if i added the widgets (in assets) only. (absence of 'missing apps' page)
2. app is not crashing when i add other assets too the in the app (like lock screen assets,KLWP's). (Missing apps page is showing)

### Reproduction Steps

i,ve tried few steps.
1. app is crashing if i added the widgets (in assets) only. (absence of 'missing apps' page)
2. app is not crashing when i add other assets too the in the app (like lock screen assets,KLWP's). (Missing apps page is showing)

### Expected behavior

app crashes & closes

### Screenshots or videos

1. app crashing - https://github.com/jahirfiquitiva/Kuper/assets/71331916/d0e06641-16ec-4e6a-ab59-4276dfc6abf6
2. app not crashing - https://github.com/jahirfiquitiva/Kuper/assets/71331916/dfa7c397-4206-44eb-8c33-bfc1871d610b

### Code and/or Logs

2023-07-05 20:37:48.765  3636-3636  DEBUG                   pid-3636                             A  Cmdline: dev.jahir.kuper.app
2023-07-05 20:37:48.765  3636-3636  DEBUG                   pid-3636                             A  pid: 3536, tid: 3574, name: DefaultDispatch  >>> dev.jahir.kuper.app <<<
2023-07-05 20:37:48.765  3636-3636  DEBUG                   pid-3636                             A        #08 pc 000000000047f898  [anon:dalvik-classes.dex extracted in memory from /data/app/~~zCP0joafXHXB_Q3VHIlcXw==/dev.jahir.kuper.app-aEZyJWcM8HgzHw9wPdrWrg==/base.apk] (dev.jahir.kuper.data.viewmodels.ComponentsViewModel$getWidgetPreviewsPathFromZip$2.invoke+16)
2023-07-05 20:37:48.765  3636-3636  DEBUG                   pid-3636                             A        #10 pc 000000000047f86c  [anon:dalvik-classes.dex extracted in memory from /data/app/~~zCP0joafXHXB_Q3VHIlcXw==/dev.jahir.kuper.app-aEZyJWcM8HgzHw9wPdrWrg==/base.apk] (dev.jahir.kuper.data.viewmodels.ComponentsViewModel$getWidgetPreviewsPathFromZip$2.invoke+8)
2023-07-05 20:37:48.765  3636-3636  DEBUG                   pid-3636                             A        #12 pc 00000000000eb6c0  [anon:dalvik-classes4.dex extracted in memory from /data/app/~~zCP0joafXHXB_Q3VHIlcXw==/dev.jahir.kuper.app-aEZyJWcM8HgzHw9wPdrWrg==/base.apk!classes4.dex] (kotlinx.coroutines.intrinsics.UndispatchedKt.startUndispatchedOrReturn+28)
2023-07-05 20:37:48.765  3636-3636  DEBUG                   pid-3636                             A        #14 pc 00000000000a7744  [anon:dalvik-classes4.dex extracted in memory from /data/app/~~zCP0joafXHXB_Q3VHIlcXw==/dev.jahir.kuper.app-aEZyJWcM8HgzHw9wPdrWrg==/base.apk!classes4.dex] (kotlinx.coroutines.BuildersKt__Builders_commonKt.withContext+136)
2023-07-05 20:37:48.765  3636-3636  DEBUG                   pid-3636                             A        #16 pc 00000000000a791c  [anon:dalvik-classes4.dex extracted in memory from /data/app/~~zCP0joafXHXB_Q3VHIlcXw==/dev.jahir.kuper.app-aEZyJWcM8HgzHw9wPdrWrg==/base.apk!classes4.dex] (kotlinx.coroutines.BuildersKt.withContext+0)
2023-07-05 20:37:48.765  3636-3636  DEBUG                   pid-3636                             A        #18 pc 0000000000480974  [anon:dalvik-classes.dex extracted in memory from /data/app/~~zCP0joafXHXB_Q3VHIlcXw==/dev.jahir.kuper.app-aEZyJWcM8HgzHw9wPdrWrg==/base.apk] (dev.jahir.kuper.data.viewmodels.ComponentsViewModel.getWidgetPreviewsPathFromZip+48)
2023-07-05 20:37:48.765  3636-3636  DEBUG                   pid-3636                             A        #20 pc 000000000048090c  [anon:dalvik-classes.dex extracted in memory from /data/app/~~zCP0joafXHXB_Q3VHIlcXw==/dev.jahir.kuper.app-aEZyJWcM8HgzHw9wPdrWrg==/base.apk] (dev.jahir.kuper.data.viewmodels.ComponentsViewModel.access$getWidgetPreviewsPathFromZip+0)
2023-07-05 20:37:48.765  3636-3636  DEBUG                   pid-3636                             A        #22 pc 000000000048021e  [anon:dalvik-classes.dex extracted in memory from /data/app/~~zCP0joafXHXB_Q3VHIlcXw==/dev.jahir.kuper.app-aEZyJWcM8HgzHw9wPdrWrg==/base.apk] (dev.jahir.kuper.data.viewmodels.ComponentsViewModel$internalLoadComponents$2.invokeSuspend+886)
2023-07-05 20:37:48.765  3636-3636  DEBUG                   pid-3636                             A        #24 pc 00000000000667c6  [anon:dalvik-classes4.dex extracted in memory from /data/app/~~zCP0joafXHXB_Q3VHIlcXw==/dev.jahir.kuper.app-aEZyJWcM8HgzHw9wPdrWrg==/base.apk!classes4.dex] (kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith+42)
2023-07-05 20:37:48.765  3636-3636  DEBUG                   pid-3636                             A        #26 pc 00000000000acd2c  [anon:dalvik-classes4.dex extracted in memory from /data/app/~~zCP0joafXHXB_Q3VHIlcXw==/dev.jahir.kuper.app-aEZyJWcM8HgzHw9wPdrWrg==/base.apk!classes4.dex] (kotlinx.coroutines.DispatchedTask.run+448)
2023-07-05 20:37:48.765  3636-3636  DEBUG                   pid-3636                             A        #28 pc 00000000000e6d72  [anon:dalvik-classes4.dex extracted in memory from /data/app/~~zCP0joafXHXB_Q3VHIlcXw==/dev.jahir.kuper.app-aEZyJWcM8HgzHw9wPdrWrg==/base.apk!classes4.dex] (kotlinx.coroutines.internal.LimitedDispatcher$Worker.run+10)
2023-07-05 20:37:48.765  3636-3636  DEBUG                   pid-3636                             A        #30 pc 00000000000ee93a  [anon:dalvik-classes4.dex extracted in memory from /data/app/~~zCP0joafXHXB_Q3VHIlcXw==/dev.jahir.kuper.app-aEZyJWcM8HgzHw9wPdrWrg==/base.apk!classes4.dex] (kotlinx.coroutines.scheduling.TaskImpl.run+6)
2023-07-05 20:37:48.765  3636-3636  DEBUG                   pid-3636                             A        #32 pc 00000000000eda06  [anon:dalvik-classes4.dex extracted in memory from /data/app/~~zCP0joafXHXB_Q3VHIlcXw==/dev.jahir.kuper.app-aEZyJWcM8HgzHw9wPdrWrg==/base.apk!classes4.dex] (kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely+2)
2023-07-05 20:37:48.765  3636-3636  DEBUG                   pid-3636                             A        #34 pc 00000000000ec5e2  [anon:dalvik-classes4.dex extracted in memory from /data/app/~~zCP0joafXHXB_Q3VHIlcXw==/dev.jahir.kuper.app-aEZyJWcM8HgzHw9wPdrWrg==/base.apk!classes4.dex] (kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask+34)
2023-07-05 20:37:48.765  3636-3636  DEBUG                   pid-3636                             A        #36 pc 00000000000ec710  [anon:dalvik-classes4.dex extracted in memory from /data/app/~~zCP0joafXHXB_Q3VHIlcXw==/dev.jahir.kuper.app-aEZyJWcM8HgzHw9wPdrWrg==/base.apk!classes4.dex] (kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker+56)
2023-07-05 20:37:48.765  3636-3636  DEBUG                   pid-3636                             A        #38 pc 00000000000ec6c0  [anon:dalvik-classes4.dex extracted in memory from /data/app/~~zCP0joafXHXB_Q3VHIlcXw==/dev.jahir.kuper.app-aEZyJWcM8HgzHw9wPdrWrg==/base.apk!classes4.dex] (kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run+0)

**Comment by jahirfiquitiva** [comment] 2023-07-17 03:39
Duplicate of #80

**Closed by jahirfiquitiva** 2023-07-17 03:39 UTC
Labels: Type: Bug, Status: Help Wanted, Status: Not Reproducible, Priority: Low
