### ISSUE TITLE
Crashses latest 2.4.9

### ISSUE THREAD

**Issue by Jacksonhayes** [jahirfiquitiva/Kuper#92] opened 2023-10-07 03:19 UTC
### Requirements

- [X] I have verified there are no duplicate active or recent bugs, questions, or requests

### Kuper Version

2.4.9

### Android Version

13.0

### Device Manufacturer

Xiaomi

### Device Name

Redmi K20 Pro

### What happened?

App crashes when opening

### Reproduction Steps

just add the widgets only as assets & make sure KWGT & KWGT Pro is installed & try to run the app

### Expected behavior

App crashes

### Code and/or Logs

Error opening trace file: No such file or directory (2)
08:47:24.919 23154-23173 dev.jahir.kuper.app                  I  PFP: 0x016ee190, ME: 0x00000000
08:47:24.939 23154-23173 dev.jahir.kuper.app                  E  Unable to match the desired swap behavior.
08:47:24.942 23154-23190 dev.jahir.kuper.app                  I  Adding additional valid usage bits: 0x8202000
08:47:25.082 23154-23154 dev.jahir.kuper.app                  W  Accessing hidden field Landroid/widget/TextView;->mCursorDrawableRes:I (max-target-p, reflection, denied)
08:47:25.115 23154-23154 dev.jahir.kuper.app                  W  Accessing hidden field Landroid/widget/TextView;->mCursorDrawableRes:I (max-target-p, reflection, denied)
08:47:25.130 23154-23154 dev.jahir.kuper.app                  D  requesting permissions: android.permission.READ_EXTERNAL_STORAGE
08:47:25.200 23154-23203 dev.jahir.kuper.app                  D  tagSocket(111) with statsTag=0xffffffff, statsUid=-1
08:47:25.530 23154-23180 dev.jahir.kuper.app                  A  Fatal signal 7 (SIGBUS), code 2 (BUS_ADRERR), fault addr 0x78f3a3c9af in tid 23180 (DefaultDispatch), pid 23154 (jahir.kuper.app)

**Comment by Jacksonhayes** [comment] 2023-10-07 03:20
Please refer to the error in log

**Comment by jahirfiquitiva** [comment] 2023-10-07 03:37
Duplicate of #80

**Closed by jahirfiquitiva** 2023-10-07 03:37 UTC
Labels: Type: Bug, Status: Duplicated, Status: Invalid
